language: python
python:
  - "2.7"
before_install:
    sudo apt-get install libgnome-keyring0
install:
  - pip install --timeout=30 pep8 --use-mirrors
  - pip install --timeout=30 pyflakes --use-mirrors
  - pip install --timeout=30 -r requirements.txt --use-mirrors --allow-external fs
  - pip install --timeout=30 -q -e . --use-mirrors
before_script:
  - make verify
script: 
  make test
after_success:
  coveralls
