language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - apt-get install python-sip python-qt4
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: python tests.py
