language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo add-apt-repository ppa:pyside
  - sudo apt-get update
  - sudo apt-get install python-pyside
install:
  - pip install --timeout=30 pep8 --use-mirrors
  - pip install --timeout=30 pyflakes --use-mirrors
  - pip install --timeout=30 -r requirements.txt --use-mirrors
  - pip install --timeout=30 -q -e . --use-mirrors
before_script:
  - make verify
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: make test
after_success:
  - coveralls
