language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -e . --use-mirrors
before_install:
  - pip install -r requirements.txt --use-mirrors
  - apt-get install python-sip python-qt4
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: python tests.py
